### ISSUE TITLE
How to open this project by an IDE ?

### ISSUE THREAD

**Issue by baodingfengyun** [sormuras/bach-demo-fxgl#1]

**Comment by sormuras** [comment]
Which IDE? 😉

There's no explicit IDE support built-in into/for Bach, yet. Thus, make use of the powers of your IDE to configure a standard Java project.

**Comment by sormuras** [comment]
In IDEA, it could look like this:
![image](https://user-images.githubusercontent.com/2319838/115380193-a0eca700-a1d2-11eb-9162-7f1a6911c610.png)

**Comment by sormuras** [comment]
Here's template repository to start an application project that is built by [🎼 Bach](https://github.com/sormuras/bach) - configured with basic Project Structure for IDEA.

📋 https://github.com/sormuras/bach-application-template

Closing this issue in hope that the screenshot and template help.

**Comment by baodingfengyun** [comment]
Thanks. The bach-application-template is the very thing I want.

**Comment by sormuras** [comment]
You're welcome!

For further Bach-releated questions (and discussions and issues) please follow-up to: https://github.com/sormuras/bach
